version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    expose:
      - 5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=3900
  backend:
    build: backend
    depends_on:
      - postgres
    ports:
      - "2000:2000"
    environment:
      - PORT=2000
      - DATABASE_URL=postgresql://user:password@postgres:5432/3900
  frontend:
    build: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:2000
